#!/usr/bin/env bash
# Bash script that displays a list of currently running processes
#	Must show all processes for all users
#	Display in a user-oriented format
#	Show process hierarchy too

ps -auxf
